version: "3.0"

services:

  api:
    build: .
    image: api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    ports:
      - "3000:3000"

  attack:
    build: .
    image: attack
    env_file: docker-compose.env
    environment:
      SERVICES: attack

  planet:
    build: .
    image: planet
    env_file: docker-compose.env
    environment:
      SERVICES: planet
