basePath: /api
definitions:
    WarMessageOutDto:
        description: ""
        properties:
            deathStar:
                type: string
                description: ""
            planet:
                type: string
                description: ""
        type: object
        required:
            - deathStar
            - planet
    ContextDamageInDto:
        description: ""
        properties: {}
        type: object
info:
    description: 'My Moleculer microservices project'
    title: moleculerjs-boilerplate
    version: 1.0.0
paths:
    /deathstar:
        post:
            operationId: DeathStarServiceFireMethod
            produces:
                - 'application/json; charset=utf-8'
            responses:
                '200':
                    description: Ok
                    schema:
                        $ref: '#/definitions/WarMessageOutDto'
            description: ""
            tags:
                - DeathStarServices
            consumes:
                - 'application/json; charset=utf-8'
            parameters:
                -
                    description: ""
                    in: body
                    name: ctx
                    required: true
                    schema:
                        $ref: '#/definitions/ContextDamageInDto'
    /planet:
        post:
            operationId: PlanetServiceDefendMethod
            produces:
                - 'application/json; charset=utf-8'
            responses:
                '200':
                    description: Ok
                    schema:
                        type: number
                        format: double
            description: ""
            tags:
                - PlanetServices
            consumes:
                - 'application/json; charset=utf-8'
            parameters:
                -
                    description: ""
                    in: body
                    name: damage
                    required: true
                    schema:
                        type: number
                    format: double
swagger: '2.0'
securityDefinitions:
    api_key:
        type: apiKey
        name: access_token
        in: query
    tsoa_auth:
        type: oauth2
        authorizationUrl: 'http://swagger.io/api/oauth/dialog'
        flow: implicit
        scopes:
            'write:pets': 'modify things'
            'read:pets': 'read things'
host: 'localhost:3000'
