basePath: /api
definitions: {}
info:
    description: 'My Moleculer microservices project'
    title: moleculerjs-boilerplate
    version: 1.0.0
paths:
    /fire:
        post:
            operationId: FireServiceFireMethod
            produces:
                - 'application/json; charset=utf-8'
            responses:
                '200':
                    description: Ok
                    schema:
                        type: string
            description: ""
            tags:
                - FireServices
            consumes:
                - 'application/json; charset=utf-8'
            parameters:
                -
                    description: ""
                    in: body
                    name: damage
                    required: true
                    schema:
                        type: number
                    format: double
    /planet:
        post:
            operationId: PlanetServiceDefendMethod
            produces:
                - 'application/json; charset=utf-8'
            responses:
                '200':
                    description: Ok
                    schema:
                        type: number
                        format: double
            description: ""
            tags:
                - PlanetServices
            consumes:
                - 'application/json; charset=utf-8'
            parameters:
                -
                    description: ""
                    in: body
                    name: damage
                    required: true
                    schema:
                        type: number
                    format: double
swagger: '2.0'
securityDefinitions:
    api_key:
        type: apiKey
        name: access_token
        in: query
    tsoa_auth:
        type: oauth2
        authorizationUrl: 'http://swagger.io/api/oauth/dialog'
        flow: implicit
        scopes:
            'write:pets': 'modify things'
            'read:pets': 'read things'
host: 'localhost:3000'
